# Generated by Django 5.2.3 on 2025-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(default=0)),
                ('location_id', models.IntegerField(default=0)),
                ('movement_id', models.IntegerField(default=0)),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
