# Generated by Django 5.2.3 on 2025-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproducts',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
