# Generated by Django 5.2.3 on 2025-06-19 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_inventoryproducts_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_from', to='Inventory.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_to', to='Inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryProducts',
        ),
        migrations.AddField(
            model_name='productmovement',
            name='product_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products'),
        ),
    ]
