# Generated by Django 5.2.3 on 2025-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_location_productmovement_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='movement_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
